### ISSUE TITLE
Data from the previous day in the forecast array in the first hour of the new day

### ISSUE THREAD

**Issue by Bnt79** [FL550/dwd_weather#189]
## Version of home_assistant
2025.2.5 (core)

## How are you running home_assistant
HAOS

## Version of the custom_component
2.1.31

## Describe the bug
If new data is retrieved via weather.get_forecasts between 00:00 and 01:00, the first data set in the array contains data from the previous day. As soon as the function is executed after 01:00, the first data set contains the data from the current day.

**Comment by FL550** [comment]
Hi @Bnt79 

are you using the normal update or are you using the hourly update rate?

**Comment by FL550** [comment]
@Bnt79 No, I mean if you have configured the hourly update in the settings of the integration.

**Comment by Bnt79** [comment]
@FL550  No, i use the normal update rate

**Comment by FL550** [comment]
This is now corrected

**Comment by Bnt79** [comment]
I updated to the new version 2.2.2. Unfortunately the behavior is still the same

**Comment by FL550** [comment]
@Bnt79 So then it might have something to do with your timezone setting. I'll check something on my own before, but thereafter I need your assistance in getting that bug. I keep you posted.

**Comment by Bnt79** [comment]
@FL550  I tested some code for my own. I changed conector.py to use HA timezone. I tested with the "get_forecast_daily" function and got the results i excpected for the forecast array.

`from homeassistant.util.dt import get_time_zone
.
.
.
def get_forecast_daily(self) -> list[Forecast] | None:
        weather_interval = 24
        from datetime import datetime, timedelta, timezone
        # get timezone fromHA
        homeassistant_timezone = get_time_zone()
        now = datetime.now(homeassistant_timezone)
        #now = datetime.now(timezone.utc)`

Regards
Marco

**Comment by FL550** [comment]
I have implemented your suggestions in 2.5.4. Thanks for providing me info to fix this.
