### ISSUE TITLE
Unexpected error fetching DWD Map Coordinator data

### ISSUE THREAD

**Issue by Dondo11** [FL550/dwd_weather#207]
See log below for error and traceback

The interesting point is the TIME parameter in the URL.  Opening the URL without it seemingly works.

## Version of home_assistant
Core 2025.5.1
OS 15.2

## How are you running home_assistant
HAOS

## Version of the custom_component
2.2.3

## Data update mode
normal

## Describe the bug
see log below

## Debug log
This error originated from a custom integration.

Logger: custom_components.dwd_weather
Source: helpers/update_coordinator.py:380
integration: Deutscher Wetterdienst (documentation, issues)
First occurred: May 14, 2025 at 15:49:07 (11 occurrences)
Last logged: 13:07:54

Unexpected error fetching DWD Map Coordinator data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwd_weather/connector.py", line 949, in async_update
    return await self._hass.async_add_executor_job(self._update)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dwd_weather/connector.py", line 956, in _update
    self._update_loop()
    ~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/dwd_weather/connector.py", line 977, in _update_loop
    self._maploop.update()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdmap.py", line 284, in update
    self._get_image(self._last_update, with_lightning=True)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simple_dwd_weatherforecast/dwdmap.py", line 329, in _get_image
    raise ConnectionError(f"Error during image request from DWD servers: {url}")
ConnectionError: Error during image request from DWD servers: `https://maps.dwd.de/geoserver/dwd/wms?service=WMS&version=1.3.0&request=GetMap&layers=dwd:Radar_rv_product_1x1km_ger,dwd:NCEW_EU,dwd:Warngebiete_Bundeslaender&bbox=46.4,4.4,55.6,16.1&width=520&height=580&srs=EPSG:4326&styles=&format=image/png&TIME=2025-05-14T13:35:00.0Z&bgcolor=0xFFFFFF

**Comment by FL550** [comment]
@Dondo11 I can't reproduce this issue. The time parameter is needed, to get the precipitation image loop. 

Do you still have this error?

**Comment by Dondo11** [comment]
Yes, I'm still seeing this error sporadically.  I've also tried to find a way to trigger it, but with no luck so far.

Perhaps a little bit of history may help:  The error apparently started occuring after I deleted my first attempt at creating the precipitation map; I was dissatisfied with the parameters I'd chosen for its appearance and couldn't find a way to modify those parameters.  Hence, I deleted the map and created a new one which looks fine now.

I've attached a core log of 10.000 lines that is flooded with plenty of ``no report for this station available`` messages without neither timestamp nor indication of origin; N.B.: I'm not implying "station" is referring to DWD station!  There are also some messages from a Harmony hub integration strewn in whose timestamps provide an idea when the "station" messages occured.

[home-assistant_2025-05-18T13-00-26.679Z.log](https://github.com/user-attachments/files/20272914/home-assistant_2025-05-18T13-00-26.679Z.log)

**Comment by Dondo11** [comment]
Addendum:  The error occurs when I switch to the dashboard showing the DWD entities, but not every time I do this. I'm attaching a screenshot of the dashboard:

![Image](https://github.com/user-attachments/assets/8b108386-a6a0-42d5-a709-6592fc3ea663)

**Comment by FL550** [comment]
Thanks for the log file. I'll try to find the reason for your error. 

Regarding the error only shown when you switch to the dashboard: this is as expected, because the map is only updated when visible. This is due to the fact, that HA only calls the image update method when shown.

**Comment by Steffen06** [comment]
@FL550 @Dondo11 I had the same error a few times myself.
If you open the link (https://maps.dwd.de/geoserver/dwd/wms?service=WMS&version=1.3.0&request=GetMap&layers=dwd:Radar_rv_product_1x1km_ger,dwd:NCEW_EU,dwd:Warngebiete_Bundeslaender&bbox=46.4,4.4,55.6,16.1&width=520&height=580&srs=EPSG:4326&styles=&format=image/png&TIME=2025-05-14T13:35:00.0Z&bgcolor=0xFFFFFF) in a new tab you get the following "error" (with http code 200):
```xml
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://maps.dwd.de/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="InvalidDimensionValue" locator="time"> Could not find a match for 'time' value: '2025-05-14T13:35:00.0Z' </ServiceException>
</ServiceExceptionReport>
```

This error says that one or more of the requested map layers (in this case):

- dwd:Radar_rv_product_1x1km_ger
- dwd:NCEW_EU (~4 hours available)
- dwd:Warngebiete_Bundeslaender (up to 4 days)

is not available (for that requested timestamp). In my experience it is in most cases the `dwd:NCEW_EU` layer. 

> I can't reproduce this issue.

Caused by DWD sporadically failing to generating a layer.

> How to test wich layer is failing

Remove one of the Layers and the try to request the remaining layers. (In this case, you cannot test it again because all levels are no longer available.)

- If it works you found the the layer that is not available for this timestamp
- otherwise test next layer and repeat

> The interesting point is the TIME parameter in the URL. Opening the URL without it seemingly works.

The Answer to this observation is that you get the **latest available** image **where all Layers are available.**

**Comment by Dondo11** [comment]
Thanks for your most helpful explanaxtion @Steffen06!!

A pragmatic solution might be to catch the 200 error, then repeat the request without the time parameter?  I for one could live with not receiving a most up-to-date image some of the time.

The ``no report for this station available`` message in my logs are **not** related to the integration, btw, but originate elsewhere.  I'm puzzled what kind of station this might refer to since there aren't any I'm aware of...

**Comment by Steffen06** [comment]
@Dondo11 you got it almost right.

> _A pragmatic solution might be to catch the 200 error_, [...]?

The 200 is a HTTP-Statuscode and implies normally that request was processed without any errors. In case of an error you normally you get an 4XX / 5XX HTTP-Statuscode to imply that the request could not be fulfilled due to an error. In this case it is also necessary to check the the requested `&format=image/png` against the replied `content-type`:
 
- image/png (No Error; The requested Image)
- text/xml;charset=UTF-8 (Error; More information's in the replied XML, encoded with UTF-8)

> [...], _then repeat the request without the time parameter_?

No, if you remove the TIME parameter you have no control over the what reference time the image has and it would break the image series (eg 3:25, 3:30, ??:?? (depending on request time), 3:40, 3:45). The proper solution is to identify the problematic layer an then retrying without it.

> The `no report for this station available` message in my logs are not related to the integration, btw, but originate elsewhere. I'm puzzled what kind of station this might refer to since there aren't any I'm aware of...

No and Yes. I think the unrelated problem is similar to issue #187 it is only a wrong condition or wrong call of this function in the integration or the underlying library ['simple_dwd_weatherforecast'](https://github.com/FL550/simple_dwd_weatherforecast). But I can say the message comes definitely from the following, linked code segment:
https://github.com/FL550/simple_dwd_weatherforecast/blob/cf81f57c4bc61566e390f86fb064041e57f13108/simple_dwd_weatherforecast/dwdforecast.py#L422-L425

> [!NOTE]
> I have not looked in to this problem further.

**Comment by FL550** [comment]
@Steffen06 Thanks for looking into this. 

> The proper solution is to identify the problematic layer an then retrying without it.

I'll think this would be the best approach, since it seems like the other requests are successful. I'll later add a debugging statement, to see from which call in a series this error arises. This allows for more finegrained error handling. 

Regarding the message `no report for this station available` this is definitely from this package. I'll look into this as well.

**Comment by FL550** [comment]
I implemented better error handling. Let's see if it reduces the amount of unnecessary log entries.

**Comment by Dondo11** [comment]
Thanks @FL550!

Updated to 2.4.1 — Let’s wait and see…

Note that I‘ll be out of the country for a few days, so I‘ll keep observing/giving feedback on things, but possible additional updates will have to wait till I‘m back.

**Comment by Dondo11** [comment]
No more hiccups re the original issue these past 2 weeks.

Very rarely still getting

<pre>
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1191
First occurred: May 28, 2025 at 19:18:14 (4 occurrences)
Last logged: June 5, 2025 at 17:40:57

Updating state for sensor.griesheim_temperatur (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.940 seconds. Please create a bug report at https://github.com/FL550/dwd_weather/issues
Updating state for sensor.griesheim_windrichtung (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.954 seconds. Please create a bug report at https://github.com/FL550/dwd_weather/issues
Updating state for sensor.griesheim_wetterbericht (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.965 seconds. Please create a bug report at https://github.com/FL550/dwd_weather/issues
Updating state for sensor.griesheim_niederschlagswahrscheinlichkeit (<class 'custom_components.dwd_weather.sensor.DWDWeatherForecastSensor'>) took 0.982 seconds. Please create a bug report at https://github.com/FL550/dwd_weather/issues
</pre>
