### ISSUE TITLE
since update incorrect temperatur shown in dwd integration

### ISSUE THREAD

**Issue by mktat81** [FL550/dwd_weather#78]
## Version of home_assistant
 2023.9.2

## Version of the custom_component
 version 2.0.0

## Describe the bug
A clear and concise description of what the bug or error is and when it happens.
since the update yesterday it didn't get the correct Temperature Information 
the integrations is currently show 26 degree if i take a look on dwd website i see 19 degree for the same area
the show information for humidity winddirection etc. are also different betweeen dwd website an integratin 

I didnot find any usefull information in the debug log but see below 
## Debug log

```text

Add your logs here.

2023-09-22 16:13:00.833 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for 48564 data in 0.000 seconds (success: True)
2023-09-22 16:13:06.905 DEBUG (MainThread) [custom_components.dwd_weather] Setup with data {'data_type': 'forecast_data', 'station_id': '48564', 'station_name': 'hamburg-fu.', 'wind_direction_type': 'DEGREES', 'hourly_update': False}
2023-09-22 16:13:07.175 INFO (SyncWorker_17) [custom_components.dwd_weather.connector] Updating hamburg-fu.
2023-09-22 16:13:07.176 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for 48564 data in 0.271 seconds (success: True)
2023-09-22 16:13:07.176 DEBUG (MainThread) [custom_components.dwd_weather] issue_time: 2023-09-22 09:00:00+00:00
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.weather] Setting up weather with id 48564_Weather and name hamburg-fu.
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Sensor async_setup_entry {'data_type': 'forecast_data', 'station_id': '48564', 'station_name': 'hamburg-fu.', 'wind_direction_type': 'DEGREES', 'hourly_update': False}
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Sensor async_setup_entry
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Weather and name Weather
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Weather Report and name Weather Report
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Temperature and name Temperature
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Dewpoint and name Dewpoint
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Pressure and name Pressure
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Wind Speed and name Wind Speed
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Wind Direction and name Wind Direction
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Wind Gusts and name Wind Gusts
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Precipitation and name Precipitation
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Precipitation Probability and name Precipitation Probability
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Precipitation Duration and name Precipitation Duration
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Cloud Coverage and name Cloud Coverage
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Visibility and name Visibility
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Sun Duration and name Sun Duration
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Sun Irradiance and name Sun Irradiance
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Fog Probability and name Fog Probability
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Humidity and name Humidity
2023-09-22 16:13:07.177 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id 48564_Forecast Time (UTC) and name Forecast Time (UTC)

if you need any further information let me know

**Comment by FL550** [comment]
I'll have a look into this the next days.

**Comment by mktat81** [comment]
I think i found the problem.
the weather station i used 'station_id': '48564', 'station_name': 'hamburg-fu.' is gone.
I deletet the integration and reinstalled using the Web UI and the station was nowhere to find so i added a different and the numbers i see now are same like on the DWD website. 

so the issue is a missing Station ;-)

**Comment by FL550** [comment]
Thanks for the update. As someone pointed out [here](https://github.com/FL550/simple_dwd_weatherforecast/issues/14) there is a problem with the stations in general. I have to check this.

**Comment by FL550** [comment]
This should now be fixed with the new version 2.0.1.

**Comment by mktat81** [comment]
did the update but could noch find 'station_id': '48564', 'station_name': 'hamburg-fu.' as i used before  in the ui list. i will try to deinstall and reinstall if this will change afterwards

**Comment by FL550** [comment]
This was my mistake, sorry. I forgot to update the packaged files. Can you please try this again?

**Comment by mktat81** [comment]
after reinstall again, the station is back with correct data 

thank you :)

**Comment by FL550** [comment]
Thank you as well for helping me finding this error :)

**Comment by mktat81** [comment]
no Problem :)

**Comment by jensrossbach** [comment]
@FL550 I had a similar problem and after reading this thread, I re-added my weather station (Löhnberg-Obershausen) again. After that, the temperature values in the new configuration are correct again, but the weather conditions are not correct. They show sunny for nearly all upcoming days but the DWD app shows rainy for Wednesday and partly cloudy for the others.

**Comment by FL550** [comment]
Hm, strange as the values are either all correct or all incorrect. There is only one weather data source for a single station. Can you please provide me a debug log?

**Comment by jensrossbach** [comment]
Here are the logs:

```
2023-10-02 18:54:18.051 DEBUG (MainThread) [custom_components.dwd_weather] Setup with data {'station_id': 'L511', 'data_type': 'mixed_data', 'station_name': 'Löhnberg-Obershausen', 'wind_direction_type': 'degrees', 'hourly_update': False}
2023-10-02 18:54:18.795 INFO (SyncWorker_8) [custom_components.dwd_weather.connector] Updating Löhnberg-Obershausen
2023-10-02 18:54:19.160 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 1.108 seconds (success: True)
2023-10-02 18:54:19.160 DEBUG (MainThread) [custom_components.dwd_weather] issue_time: 2023-10-02 15:00:00+00:00
2023-10-02 18:54:24.248 DEBUG (MainThread) [custom_components.dwd_weather.weather] Setting up weather with id L511_Weather and name Löhnberg-Obershausen
2023-10-02 18:54:24.250 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Sensor async_setup_entry {'station_id': 'L511', 'data_type': 'mixed_data', 'station_name': 'Löhnberg-Obershausen', 'wind_direction_type': 'degrees', 'hourly_update': False}
2023-10-02 18:54:24.250 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Sensor async_setup_entry
2023-10-02 18:54:24.250 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Weather and name Weather
2023-10-02 18:54:24.250 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Weather Report and name Weather Report
2023-10-02 18:54:24.250 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Temperature and name Temperature
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Dewpoint and name Dewpoint
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Pressure and name Pressure
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Wind Speed and name Wind Speed
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Wind Direction and name Wind Direction
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Wind Gusts and name Wind Gusts
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Precipitation and name Precipitation
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Precipitation Probability and name Precipitation Probability
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Precipitation Duration and name Precipitation Duration
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Cloud Coverage and name Cloud Coverage
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Visibility and name Visibility
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Sun Duration and name Sun Duration
2023-10-02 18:54:24.251 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Sun Irradiance and name Sun Irradiance
2023-10-02 18:54:24.252 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Fog Probability and name Fog Probability
2023-10-02 18:54:24.252 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Humidity and name Humidity
2023-10-02 18:54:24.252 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Forecast Time (UTC) and name Forecast Time (UTC)
2023-10-02 18:54:24.252 DEBUG (MainThread) [custom_components.dwd_weather.sensor] Setting up sensor with id L511_Report Time (UTC) and name Report Time (UTC)
2023-10-02 18:55:23.576 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.001 seconds (success: True)
2023-10-02 18:56:23.576 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.001 seconds (success: True)
2023-10-02 18:57:23.576 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.001 seconds (success: True)
2023-10-02 18:58:23.577 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.001 seconds (success: True)
2023-10-02 18:59:23.576 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.001 seconds (success: True)
2023-10-02 19:00:24.199 INFO (SyncWorker_5) [custom_components.dwd_weather.connector] Updating Löhnberg-Obershausen
2023-10-02 19:00:24.205 DEBUG (MainThread) [custom_components.dwd_weather] Finished fetching DWD Weather Coordinator for L511 data in 0.629 seconds (success: True)
```

This is how the data in the weather entity today looks like:

![image](https://github.com/FL550/dwd_weather/assets/5118924/0239fe12-7726-40e7-94ec-fa442df9ca07)
![image](https://github.com/FL550/dwd_weather/assets/5118924/57ddb364-b415-4b4b-ba32-e90521fe8b88)

This is what the DWD app says:

![image](https://github.com/FL550/dwd_weather/assets/5118924/c377bae0-64ff-47d6-8ba4-a72d493898cd)

**Comment by FL550** [comment]
I have updated the integration to v2.0.2 to provide better debugging capabilities. Can you please send me the new debug logs and also download the file from DWD at the same time and upload it here: https://opendata.dwd.de/weather/local_forecasts/mos/MOSMIX_L/single_stations/L511/kml/MOSMIX_L_LATEST_L511.kmz

**Comment by jensrossbach** [comment]
Here is the log and the downloaded file from DWD:
[dwd_weather_L511.log](https://github.com/FL550/dwd_weather/files/12820465/dwd_weather_L511.log)
[MOSMIX_L_LATEST_L511.zip](https://github.com/FL550/dwd_weather/files/12820468/MOSMIX_L_LATEST_L511.zip)

![image](https://github.com/FL550/dwd_weather/assets/5118924/71f3ee35-95ca-4c60-b4a5-a03b5935d435)
![Bildschirmfoto 2023-10-05 um 17 53 37](https://github.com/FL550/dwd_weather/assets/5118924/43dfac3a-53b8-4958-bf45-378d9af14c66)

**Comment by FL550** [comment]
I might have found the solution, as the weather conditions are reported by DWD as `partly-cloudy`. I will update the library to reflect this better.

**Comment by jensrossbach** [comment]
Great, can you also check the other weather conditions, because there was also a condition with partly cloudy and a bit of rain which was shown as sunny.

**Comment by FL550** [comment]
Sunny shouldn't be the case after the update. And to be displayed as rainy, it has to be more than two hours per day.

**Comment by FL550** [comment]
This is now fixed in [v2.0.3](https://github.com/FL550/dwd_weather/releases/tag/v2.0.3). Please let me know if not and otherwise please close this issue.

**Comment by GerdRuetten** [comment]
> This is now fixed in [v2.0.3](https://github.com/FL550/dwd_weather/releases/tag/v2.0.3). Please let me know if not and otherwise please close this issue.

Confirm!
Attention: Select the correct station, if you see duplicate station entities in the selectbox

**Comment by jensrossbach** [comment]
It's better now, but still not optimal in my opinion.

This is what the DWD app says:
![Bildschirmfoto 2023-10-06 um 18 27 36](https://github.com/FL550/dwd_weather/assets/5118924/243d1324-1fd0-485e-b93e-925b91ff8b5c)

This is the weather data from the other DWD weather custom component in HACS:
![Bildschirmfoto 2023-10-06 um 18 28 51](https://github.com/FL550/dwd_weather/assets/5118924/7f24b58d-ac5c-4279-bcc3-70308ec04f01)

And this is the weather data from your integration:
![Bildschirmfoto 2023-10-06 um 18 26 24](https://github.com/FL550/dwd_weather/assets/5118924/f7cd1999-1093-49d5-b786-800fbd05339f)

The values from the other integration are also not perfect, but at least the icon with cloud and sun for instance fits better. Also the min/max temperature values are correct for all days but not in case of this integration.

**Comment by FL550** [comment]
But the condition icons are exactly the same as in the DWD app, which I consider as master?

And the reason for the temperatures are probably rounding differences.

**Comment by jensrossbach** [comment]
> But the condition icons are exactly the same as in the DWD app, which I consider as master?

Not exactly, the DWD app shows clouds with a sun and your integration shows only clouds (or only sun like in case of today).

> And the reason for the temperatures are probably rounding differences.

Okay, so the integration is rounding the values to a whole integer?

**Comment by FL550** [comment]
> Not exactly, the DWD app shows clouds with a sun and your integration shows only clouds (or only sun like in case of today).

Homeassistant only offers the states sunny, partly-cloudy and cloudy for only cloudy. Within the DWD app there is at least one state more. I don't think I could get a better fit.


> Okay, so the integration is rounding the values to a whole integer?

Yes

**Comment by jensrossbach** [comment]
For me it looks like as you map partly-cloudy to cloudy (because the icon with clouds only is shown, third picture above). The other DWD weather integration seems to use the partly-cloudy state (second picture above).

**Comment by FL550** [comment]
It isn't a direct mapping, as there are only hourly data points and no daily summary available.

Can you please confirm this in a few days, as for me it fits.

**Comment by GerdRuetten** [comment]
@FL550 

Isn't this the all possible conditions

![image](https://github.com/FL550/dwd_weather/assets/97361636/23aa853c-4522-4be1-b21a-dd5fd8c4f584)

See

https://www.home-assistant.io/integrations/weather/

**Comment by FL550** [comment]
Yes they are and I am using all of these. But for clouds only without precipitation, there are only the three.

**Comment by jensrossbach** [comment]
I think it's okay now. Issue can be closed from my point of view.
